Metrics/ParameterLists:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/MethodName:
  Enabled: false
